# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 21:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField()),
                ('status', models.BooleanField(choices=[(False, 'NEW'), (True, 'SENT')], default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('changed_at', models.DateTimeField()),
                ('first_name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('birth_day', models.DateField()),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('passport_number', models.CharField(max_length=10)),
                ('score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(850)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('changed_at', models.DateTimeField()),
                ('started_rotating_at', models.DateTimeField()),
                ('ended_rotating_at', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('C', 'потреб'), ('M', 'ипотека'), ('A', 'автокредит'), ('S', 'КМСБ')], max_length=1)),
                ('min_score', models.IntegerField(validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(850)])),
                ('max_score', models.IntegerField(validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(850)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credits.Organization'),
        ),
        migrations.AddField(
            model_name='application',
            name='customer_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credits.CustomerProfile'),
        ),
        migrations.AddField(
            model_name='application',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credits.Offer'),
        ),
    ]
